Implemented bash-cli.
vvselischev/Software-Design pull request #1
Opened 2020-02-02 17:03 UTC by vvselischev

2020-02-16 14:55 UTC, yurii-litvinov requested changes
Вообще, понравилось, что написано очень "архитектурно", как будто на Java, а не на Питоне. Питон-программисту, наверное, было бы тяжело читать такой код, но для курса по архитектуре самое то.

По функциональности:
- под виндой не работают внешние команды
  ```
  > git
  not enough values to unpack (expected 2, got 1) 
  ```
- имеет смысл ругаться на пайп, за которым ниего нет (`echo 1 |`)
- три теста под виндой не прошли

2020-02-16 14:55 UTC, yurii-litvinov commented on Bash-CLI/README.md
> +Объект Interpreter преобразует команду из строкого представление в токенизированное, используя объект Parser.
из строкого представлениЯ :)

2020-02-16 14:55 UTC, yurii-litvinov commented on Bash-CLI/src/bash/interpreter/builtins/cat.py
> +        if len(self._args) >= 2:
Фабрика ведь уже проверяет корректность аргументов. Не то чтобы лишние проверки --- это плохо, но возникает вопрос, кто идеологически должен за это отвечать

2020-02-16 14:55 UTC, yurii-litvinov commented on Bash-CLI/src/bash/parser/builtin_factories/exit_factory.py
> +        return command
Можно заметить, что все фабрики очень похожи, так что если перенести проверку аргументов в сами команды, а разбирательство с кавычками у параметров --- в парсер, то можно было бы сделать проще, одну фабрику как мапу имени команды на функцию, которая просто возвращает объект (то что сейчас FactoryManager делает). С другой стороны, овердизайн приветствуется, а предлагаемая мной модификация попахивает функциональным стилем, так что так тоже ок.

2020-02-16 14:55 UTC, yurii-litvinov commented on Bash-CLI/src/bash/parser/builtin_factories/factory_manager.py
> +class FactoryManager:
Вообще, этому  классу тоже нужен комментарий

2020-02-16 14:55 UTC, yurii-litvinov commented on Bash-CLI/src/bash/parser/builtin_factories/pipe_factory.py
> +            factory = self._factory_manager.choose_factory(tokenized_command)
А это даже не совсем фабрика, а скорее часть парсера. Принцип единственности ответственности и всё такое, тут и выполняется разбор строки, и собирается пайп. Хотя тоже можно не переделывать, разве что, может, переименовать класс.

2020-02-27 15:33 UTC, vvselischev commented on Bash-CLI/src/bash/parser/builtin_factories/pipe_factory.py
> +            factory = self._factory_manager.choose_factory(tokenized_command)
Всё-таки разбор строки выполняется объектом Tokenized (он выдаёт список tokenized-команд). PipeFactory просто выстраивает их в исполняемый пайп. Можно переименовать в PipeCreator, но не вижу смысла.

2020-02-27 15:41 UTC, vvselischev commented
> По функциональности:
> 
> * под виндой не работают внешние команды
>   ```
>   > git
>   not enough values to unpack (expected 2, got 1) 
>   ```

Очень странно, локально на винде всё отрабатывает.
Запускаю под python 3.8.1, git 2.11.0.windows.1

![image](https://user-images.githubusercontent.com/19926338/75455763-c72a0480-598a-11ea-97ee-bcef6eae028a.png)

Можно узнать версию питона и гита, на которых падает?

2020-02-27 16:03 UTC, vvselischev commented on Bash-CLI/src/bash/interpreter/builtins/cat.py
> +        if len(self._args) >= 2:
Да, у меня тоже возникал такой вопрос, но в итоге решил, что лучше всё же проверить.

2020-02-27 16:04 UTC, vvselischev commented on Bash-CLI/src/bash/parser/builtin_factories/factory_manager.py
> +class FactoryManager:
Fixed

2020-04-12 19:07 UTC, yurii-litvinov approved these changes
Да, сейчас всё ок, git тоже работает как надо. Зачтена.

2020-04-12 19:07 UTC, yurii-litvinov commented on Bash-CLI/README.md
> +Объект Interpreter преобразует команду из строкого представления в токенизированное, используя объект Parser.
строко**во**го :)

2021-04-25 20:53 UTC, merged